version: '3.5'
services:
  app:
    container_name: app
    restart: always
    build: .
    links:
      - mongo
    env_file:
      - ./.env
    volumes:
      - ./:/app
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
